### ISSUE TITLE
Portfolio Checklist

### ISSUE THREAD

**Issue by DavidLagou** [DavidLagou/mdia-4590#10]
### Browsers Support
- [x] Responsive in ALL viewports
- [x] Chrome
- [x] Safari
- [x] Edge
- [x] Internet Explorer 11
- [x] FireFox

### Code & Optimization 
- [x] 404 page created
- [x] All images under 1MB
- [x] All CSS classes and ID's use the same naming convention
- [x] All images have ALT text
- [x] All pages under 2.5 MB
- [x] Page Speed under 2.5s
- [x] All complex functions properly commented

### Design & UI
- [x] Logo implemented 
- [x] Consistent color theme 
- [x] CSS breakpoints added
- [x] Each Web development artifact thumbnail has the same browser image template.
- [x] Consitent contrast on header image and text

### Content 
- [x] No spelling mistakes
- [x] Each artifact on Github must be linked properly

### SEO 
- [x] All pages must have proper SEO
